services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://165.227.225.47:5000
    depends_on:
      - api

  api:
    build: 
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=localhost
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    environment:
      - DB_HOST=localhost
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_FOOTBALL_KEY=${API_FOOTBALL_KEY}

build:
  docker:
    web: frontend/Dockerfile
    api: Dockerfile.web
    scheduler: scheduler/Dockerfile
