"""Database access home for football data queries and mutations."""

from football_intelligence.database.football import (
    FootballQueryError,
    PostgresReadOnlyRunner,
    ReadOnlyFootballQueries,
    bulk_insert_formations,
    bulk_insert_odds,
    combine_stats,
    create_future_tables,
    create_match_result_predictions_table,
    create_odds_table,
    create_tables,
    dict_to_sqlite,
    drop_future_tables,
    drop_tables,
    get_from_matches,
    get_from_standings,
    get_future_matches_with_odds,
    get_latest_predictions,
    load_from_postgres,
    prune_all_future_features,
    prune_old_future_features,
    save_predictions_to_db,
    update_processed_status,
    upsert_records,
)

__all__ = [
    "FootballQueryError",
    "PostgresReadOnlyRunner",
    "ReadOnlyFootballQueries",
    "bulk_insert_formations",
    "bulk_insert_odds",
    "combine_stats",
    "create_future_tables",
    "create_match_result_predictions_table",
    "create_odds_table",
    "create_tables",
    "dict_to_sqlite",
    "drop_future_tables",
    "drop_tables",
    "get_from_matches",
    "get_from_standings",
    "get_future_matches_with_odds",
    "get_latest_predictions",
    "load_from_postgres",
    "prune_all_future_features",
    "prune_old_future_features",
    "save_predictions_to_db",
    "update_processed_status",
    "upsert_records",
]
