# Dictionary mapping countries to continents
COUNTRY_TO_CONTINENT = {
    # Europe
    'Albania': 'Europe',
    'Andorra': 'Europe',
    'Armenia': 'Europe',
    'Austria': 'Europe',
    'Azerbaijan': 'Europe',
    'Belarus': 'Europe',
    'Belgium': 'Europe',
    'Bosnia': 'Europe',
    'Bulgaria': 'Europe',
    'Croatia': 'Europe',
    'Cyprus': 'Europe',
    'Czech-Republic': 'Europe',
    'Denmark': 'Europe',
    'England': 'Europe',
    'Estonia': 'Europe',
    'Faroe-Islands': 'Europe',
    'Finland': 'Europe',
    'France': 'Europe',
    'Georgia': 'Europe',
    'Germany': 'Europe',
    'Gibraltar': 'Europe',
    'Greece': 'Europe',
    'Hungary': 'Europe',
    'Iceland': 'Europe',
    'Ireland': 'Europe',
    'Israel': 'Europe',
    'Italy': 'Europe',
    'Kazakhstan': 'Europe',
    'Kosovo': 'Europe',
    'Latvia': 'Europe',
    'Liechtenstein': 'Europe',
    'Lithuania': 'Europe',
    'Luxembourg': 'Europe',
    'Malta': 'Europe',
    'Moldova': 'Europe',
    'Montenegro': 'Europe',
    'Netherlands': 'Europe',
    'Northern-Ireland': 'Europe',
    'Norway': 'Europe',
    'Poland': 'Europe',
    'Portugal': 'Europe',
    'Romania': 'Europe',
    'Russia': 'Europe',
    'San-Marino': 'Europe',
    'Scotland': 'Europe',
    'Serbia': 'Europe',
    'Slovakia': 'Europe',
    'Slovenia': 'Europe',
    'Spain': 'Europe',
    'Sweden': 'Europe',
    'Switzerland': 'Europe',
    'Turkey': 'Europe',
    'Ukraine': 'Europe',
    'Wales': 'Europe',

    # Africa
    'Algeria': 'Africa',
    'Angola': 'Africa',
    'Benin': 'Africa',
    'Botswana': 'Africa',
    'Burkina-Faso': 'Africa',
    'Burundi': 'Africa',
    'Cameroon': 'Africa',
    'Congo': 'Africa',
    'Congo-DR': 'Africa',
    'Egypt': 'Africa',
    'Eswatini': 'Africa',
    'Ethiopia': 'Africa',
    'Gabon': 'Africa',
    'Gambia': 'Africa',
    'Ghana': 'Africa',
    'Guinea': 'Africa',
    'Ivory-Coast': 'Africa',
    'Kenya': 'Africa',
    'Lesotho': 'Africa',
    'Liberia': 'Africa',
    'Libya': 'Africa',
    'Malawi': 'Africa',
    'Mali': 'Africa',
    'Mauritania': 'Africa',
    'Mauritius': 'Africa',
    'Morocco': 'Africa',
    'Namibia': 'Africa',
    'Nigeria': 'Africa',
    'Rwanda': 'Africa',
    'Senegal': 'Africa',
    'Somalia': 'Africa',
    'South-Africa': 'Africa',
    'Sudan': 'Africa',
    'Tanzania': 'Africa',
    'Togo': 'Africa',
    'Tunisia': 'Africa',
    'Uganda': 'Africa',
    'Zambia': 'Africa',
    'Zimbabwe': 'Africa',

    # Asia
    'Bahrain': 'Asia',
    'Bangladesh': 'Asia',
    'Bhutan': 'Asia',
    'Cambodia': 'Asia',
    'China': 'Asia',
    'Chinese-Taipei': 'Asia',
    'Hong-Kong': 'Asia',
    'India': 'Asia',
    'Indonesia': 'Asia',
    'Iran': 'Asia',
    'Iraq': 'Asia',
    'Japan': 'Asia',
    'Jordan': 'Asia',
    'Kuwait': 'Asia',
    'Kyrgyzstan': 'Asia',
    'Laos': 'Asia',
    'Lebanon': 'Asia',
    'Macao': 'Asia',
    'Macedonia': 'Asia',
    'Malaysia': 'Asia',
    'Maldives': 'Asia',
    'Mongolia': 'Asia',
    'Myanmar': 'Asia',
    'Nepal': 'Asia',
    'Oman': 'Asia',
    'Pakistan': 'Asia',
    'Palestine': 'Asia',
    'Philippines': 'Asia',
    'Qatar': 'Asia',
    'Saudi-Arabia': 'Asia',
    'Singapore': 'Asia',
    'South-Korea': 'Asia',
    'Syria': 'Asia',
    'Tajikistan': 'Asia',
    'Thailand': 'Asia',
    'Turkmenistan': 'Asia',
    'United-Arab-Emirates': 'Asia',
    'Uzbekistan': 'Asia',
    'Vietnam': 'Asia',
    'Yemen': 'Asia',

    # North America
    'Antigua-And-Barbuda': 'North America',
    'Aruba': 'North America',
    'Barbados': 'North America',
    'Belize': 'North America',
    'Bermuda': 'North America',
    'Canada': 'North America',
    'Costa-Rica': 'North America',
    'Cuba': 'North America',
    'Curacao': 'North America',
    'Dominican-Republic': 'North America',
    'El-Salvador': 'North America',
    'Grenada': 'North America',
    'Guadeloupe': 'North America',
    'Guatemala': 'North America',
    'Haiti': 'North America',
    'Honduras': 'North America',
    'Jamaica': 'North America',
    'Mexico': 'North America',
    'Nicaragua': 'North America',
    'Panama': 'North America',
    'Trinidad-And-Tobago': 'North America',
    'USA': 'North America',

    # South America
    'Argentina': 'South America',
    'Bolivia': 'South America',
    'Brazil': 'South America',
    'Chile': 'South America',
    'Colombia': 'South America',
    'Ecuador': 'South America',
    'Paraguay': 'South America',
    'Peru': 'South America',
    'Suriname': 'South America',
    'Uruguay': 'South America',
    'Venezuela': 'South America',

    # Oceania
    'Australia': 'Oceania',
    'Fiji': 'Oceania',
    'New-Zealand': 'Oceania',

    # Special cases
    'Crimea': 'Europe',  # Geographically in Europe
    'World': 'World'     # Special case for international teams
}